### ISSUE TITLE
Create a local version of input-elasticsearch to obtain aggreagtion

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#10]
related to:

logstash-plugins/logstash-input-elasticsearch#90

**Comment by kjgarza** [comment]
will need to install the gem at certain poitn during dockeriamge creation. so far it works after logstash started.
requires domify gemfile and run a command

**Comment by mfenner** [comment]
Can you create a fork of this gem and install it during docker image creation? Rather than a local version?

**Comment by kjgarza** [comment]
fixed in: 421f8f2

**Comment by kjgarza** [comment]
Now is installed during image creation but well they are going to release  the change eventually. So I was thinking once they do that we can just install the gem as normal.

**Comment by mfenner** [comment]
I understand, but I would prefer installing a gem from GitHub over using a local copy.
