### ISSUE TITLE
Setup Rspec for testing filtering/processing

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#2]
Logstash uses Jruby and I haven't found a standadrd setup for rspec. 
child datacite/datacite#302

Some solutions but do not address the setup:

https://jsosic.wordpress.com/tag/logstash-rspec/
https://stackoverflow.com/questions/33523395/testing-custom-logstash-filters
https://github.com/ahahtyler/logstash-filter-cloudfoundry/blob/master/lib/logstash/filters/cloudfoundry.rb

Things to investigate:
- How to setup rspec in this pipeline ?

child  https://github.com/CDLUC3/Make-Data-Count/issues/44

**Comment by kjgarza** [comment]
blockers: 
-   GROK filter: undefined method `pattern_path' for LogStash::Environment:Module 
- REST filter: Invalid URL or request spec: '[:get, "https://api.datacite.org/works?id=%{doi}", {:params=>{"id"=>"%{[doi]}"}}]', expected a String or Hash!

**Comment by kjgarza** [comment]
another blocker
> Gem::LoadError: You have already activated jar-dependencies 0.3.2, but your Gemfile requires jar-dependencies 0.3.12. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem

**Comment by kjgarza** [comment]
I have a blocker and i need a second pair of eyes on it @mfenner  . Strategies to fix the problem:

1. Second pair of eyes to look at the problem
2. Return to the elastic image an try to fix the blocker we have there.
3. Do testing using something different to rspec

**Comment by mfenner** [comment]
@kjgarza Something I don't understand is whether or not this project requires JRuby. MRI Ruby will always be better supported by Ruby libraries.

**Comment by kjgarza** [comment]
That is another strategy  that I probably need to look as well. What I have seen so far is :

- `At this point only JRuby is supported for development and production.`  --https://github.com/elastic/logstash/issues/3233
https://stackoverflow.com/questions/39320872/execute-ruby-as-pipeline-input-for-logstash
-  I used the passeger-full image with ruby and got this error on build: `The logstash-core-api need to be build on jruby`

So it seems to indicate that indeed we need Jruby. 
NB. **this does not AFFECT logstash pipeline. the pipeline works, but the testing setup is not workin**

**Comment by mfenner** [comment]
Ok. then we need to go with JRuby. Then you have to go through the fun of sorting out dependencies. You could use another testing framework, but I would assume Rspec works with JRuby.

passenger-docker with JRuby seems to be the right base image to start.
