### ISSUE TITLE
Document log processor for Usage Report

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#26]
- [ ] Usage event fixing
-  [x] documentation for anybody to use it as docker-compose up
-  [ ] better folders for put logs
-  [x] document the client
-  [x] make nicer commands for create the report
-  [x] make nicer command to clean the index
-  [ ] make nicer command to clean the pipeline

N.B this is not necessary for Resolution Logs processing.

**Comment by kjgarza** [comment]
Readme has the basic procedure :  https://github.com/datacite/shiba-inu/blob/master/README.md

**Comment by mfenner** [comment]
Closing the issue.
