### ISSUE TITLE
Error connecting to ES

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#30]
Failed to install template. {:message=>"bad component(expected absolute path component): _template/logstash", :class=>"URI::InvalidComponentError", :backtrace=>["uri:classloader:/META-INF

parametrise folder for template

**Comment by kjgarza** [comment]
[2019-02-18T14:11:59,074][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<URI::InvalidComponentError: bad component(expected absolute path component): _template/logstash>}

it seems to be that we need to update the amazon_es plugin, it doesn't load the template for the index. but we need the new release of the filter.


https://github.com/awslabs/logstash-output-amazon_es/issues/105

**Comment by kjgarza** [comment]
current error:

````

Encountered a retryable error. Will Retry with exponential backoff {:code=>413, :url=>"http://vpc-elasticsearch-test-ejxgdtvxo76tzpax6kwet64ipu.eu-west-1.es.amazonaws.com:80/_bulk

```

**Comment by mfenner** [comment]
Closing the issue. Open new issue when needed.
