### ISSUE TITLE
Transition to Fargate

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#31]
https://datacite.atlassian.net/wiki/spaces/TEC/pages/758120469/How+to+SSH+into+Docker+containers

https://github.com/datacite/mastino/commit/758184ad65e20ad98b7af53d02db9238b15ffaf1

**Comment by kjgarza** [comment]
fix https://github.com/datacite/mastino/commit/3f3d15589e6247131a76980ed033b32a51c2c88b

**Comment by mfenner** [comment]
Closing, as the service is currently not active.
