### ISSUE TITLE
Define Storage solution for Resolution logs

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#4]
Currently logs sit in the DEv- EC2 inance but for the use in production with the piepeline we should think in a better place to store them. 
The result will indicate how the pipeline consumes them.
child datacite/datacite#302

Questions:
- What the best solutiion to store the logs?
- IF it is S3, the how to set it up for CNRI to provide the logs?

**Comment by richardhallett** [comment]
Additional thoughts:
1) You can expose S3 as a filesystem with FTP in front of, but it does mean running an FTP server somewhere.
2) What's the storage length of these logs, is it process and forget? or possibly usage later. S3 and such do have a cost associated, but you can archive into long term storage via glacier too.
3) Depending on user preference other options for getting logs might be just a regular html form.

**Comment by mfenner** [comment]
How do we get the logs? Does CNRI send them to us, or are we fetching them from CNRI?

I think S3 and variations (e.g. Glacier) are the best fit.

**Comment by kjgarza** [comment]
CNRI prefers that we fetch them from them. I would think that is something that can be agreed between CNRI and DataCite. It would require less work if received from them (as we used to a year ago). 

S3 it has good integration in logstash so it would streamline the whole pipeline significantly.

**Comment by kjgarza** [comment]
consider to use filebeat https://www.elastic.co/products/beats/filebeat

**Comment by kjgarza** [comment]
I think this is completed we already put logs in S3, so there is no need of finding further solutions.
The file merging in being done through the client in the logs processor, so there is no need to use FileBeat anymore.

**Comment by mfenner** [comment]
Makes sense.
