### ISSUE TITLE
Outputing logs from pipeline

### ISSUE THREAD

**Issue by kjgarza** [datacite/shiba-inu#5]
Several outputs should be considered for the pipeline:
- for resolution logs reports (to sashimi)
- for resolution logs in csv format (to S3 ?)
- for events  (to lagottino)
- for stats ( to ???)

questions
- All this outputs might reuired also different pipelines, investgate the differences?
- CSV files should be stored somewhere, where? s3?

**Comment by kjgarza** [comment]
We will deal with this one in a different milestone

**Comment by mfenner** [comment]
Closing this epic because of inactivity.
